global:
  registry: harbor.fabrique.social.gouv.fr
  imageProject: fabrique
  imageRepository: demande-rc

app:
  ~needs: [build-app]
  imagePackage: app
  containerPort: 8080

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        registrySecretRefName: harbor
        skipExisting: true
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"
